name: Build & Publish

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9a-ZA-Z-+.]+'
  workflow_dispatch:
    inputs:
      BuildConfiguration:
        description: "Build Configuration"
        required: true

env:
  buildConfiguration: Release

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}

      - name: 'Run: NUKE'
        run: ./build.cmd GitHubBuild --configuration ${{ env.buildConfiguration }}

      - name: 'Publish: artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          path: |
            ${{ github.workspace }}/artifacts/*.nupkg
            ${{ github.workspace }}/artifacts/*.snupkg

      - name: Push (Release)
        uses: lethek/os-specific-run@v1.0.6
        with:
          linux: dotnet nuget push "${{ github.workspace }}/artifacts/*.nupkg" -s ${{ secrets.NUGET_SOURCE }} -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
          windows: dotnet nuget push "${{ github.workspace }}\artifacts\*.nupkg" -s ${{ secrets.NUGET_SOURCE }} -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
